### ISSUE TITLE
bumping up tags only

### ISSUE THREAD

**Issue by nkpgardose** [K-Phoen/semver-release-action#24]
Hello! I really liked this solution on doing git tags & release based on labels of an PR.

Is there a possible way or example on how to bump up version on tags only but not execute release?

**Comment by K-Phoen** [comment]
That's currently not possible... but it will soon be ;)

**Comment by K-Phoen** [comment]
The latest version allows this behavior by configuring a different *release strategy*:

```yaml
name: Release

on:
  pull_request:
    types: closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
          release_strategy: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
