### ISSUE TITLE
Add support for updating tags

### ISSUE THREAD

**Issue by smokedlinq** [K-Phoen/semver-release-action#56]
I am trying to use this to get the GitHub Actions practice of tags for versioning, e.g. release vX.Y.Z but also create/update the vX.Y and vX tags. Right now when it tries to update the tag it returns the error: `422 Reference already exists`. It also looks like it is not respecting the tag_format for the minor and major steps.

Example workflow:

```yaml

    steps:
    - id: patch
      uses: k-phoen/semver-release-action@v1.3.2 
      with:
        release_branch: main
        release_strategy: release
        tag_format: v%major%.%minor%.%patch%
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - id: minor
      uses: k-phoen/semver-release-action@v1.3.2 
      with:
        release_branch: main
        release_strategy: none
        tag_format: v%major%.%minor%
        tag: ${{ steps.patch.outputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - id: major
      uses: k-phoen/semver-release-action@v1.3.2 
      with:
        release_branch: main
        release_strategy: none
        tag_format: v%major%
        tag: ${{ steps.patch.outputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
